'use strict';
/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
  let sN = s.length, tN = sN + 1, map = {};
  for (let i = 0; i < sN; i++) {
    let c = s[i];
    if (!map[c]) map[c] = 0;
    map[c]++;
  }
  for (let i = 0; i < tN; i++) {
    let c = t[i];
    //如果c在s中没有出现过，或者在t中出现的次数比s中的多，那一定就是它
    if (map[c] === undefined || --map[c] === -1) return t[i];
  }
};

findTheDifference = function(s, t) {
  let N = s.length, result = t[N].charCodeAt();
  for (let i = 0; i < N; i++) {
    result ^= s[i].charCodeAt() ^ t[i].charCodeAt();
  }
  return String.fromCharCode(result);
};

let s = "abcde", t = "abfcde";
//s = "a", t = "aa";
console.log(findTheDifference(s, t));
